{% set name = "pyroaring" %}
{% set version = "0.3.3" %}

# pyroaring compiles against a specific release of the CRoaring source
{% set CROARING_VERSION = "0.3.3" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  - url: https://github.com/Ezibenroc/PyRoaringBitMap/archive/{{ version }}.tar.gz
    sha256: e8cd32c6afcc3748f0162a1afdf81a4758ba7e25a1708461a7aab92b32e4a3db
    patches:
      # pyroaring/setup.py normally sets some version constants from git.
      # This patch just hard-codes the versions since we're building from a tarball.
      # If you bump the pyroaring version, you'll need to update this patch, too.
      - patches/hardcode-versions-{{ version }}.patch

  # The git repo includes CRoaring as a submodule, but we're using a tarball,
  # so we download CRoaring as a second source.
  - url: https://github.com/RoaringBitmap/CRoaring/archive/v{{ CROARING_VERSION }}.tar.gz
    sha256: 10ae2c0e681bda7a0d3974196d2150cc68beda0fb64b24e87251eaa83d08d07e
    folder: CRoaring

build:
  number: 0
  script: {{ PYTHON }} -m pip install --no-deps --ignore-installed .

requirements:
  build:
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
  host:
    - python
    - pip
    - cython
  run:
    - python

test:
  imports:
    - pyroaring

about:
  home: https://github.com/Ezibenroc/PyRoaringBitMap
  dev_url: https://github.com/Ezibenroc/PyRoaringBitMap
  doc_url: https://pyroaringbitmap.readthedocs.io/en/stable/?badge=stable

  license: MIT
  license_family: MIT
  license_file:
    - LICENSE
    - LICENSE_CRoaring

  summary: An efficient and light-weight ordered set of 32-bit integers
  description: |
    An efficient and light-weight ordered set of 32-bit integers
    This is a Python wrapper for the C library [CRoaring][1].

    [1]: https://github.com/RoaringBitmap/CRoaring

extra:
  recipe-maintainers:
    - stuarteberg
    - Ezibenroc
