{% set name = "pyroaring" %}
{% set version = "0.3.0" %}

# pyroaring compiles against a specific release of the CRoaring source
{% set CROARING_VERSION = "0.2.66" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  - url: https://github.com/Ezibenroc/PyRoaringBitMap/archive/{{ version }}.tar.gz
    sha256: ba17837be6bda169114666657cb8c0773e7e55faac6219d8d125584cb0089440
    patches:
      # pyroaring/setup.py normally sets some version constants from git.
      # This patch just hard-codes the versions since we're building from a tarball.
      # If you bump the pyroaring version, you'll need to update this patch, too.
      - patches/hardcode-versions-{{ version }}.patch

  # The git repo includes CRoaring as a submodule, but we're using a tarball,
  # so we download CRoaring as a second source.
  - url: https://github.com/RoaringBitmap/CRoaring/archive/v{{ CROARING_VERSION }}.tar.gz
    sha256: df98bd8f6ff09097ada529a004af758ff4d33faf6a06fadf8fad9a6533afc241
    folder: CRoaring

build:
  number: 0
  script: {{ PYTHON }} -m pip install --no-deps --ignore-installed .

requirements:
  build:
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
  host:
    - python
    - pip
    - cython
  run:
    - python

test:
  imports:
    - pyroaring

about:
  home: https://github.com/Ezibenroc/PyRoaringBitMap
  dev_url: https://github.com/Ezibenroc/PyRoaringBitMap
  doc_url: https://pyroaringbitmap.readthedocs.io/en/stable/?badge=stable

  license: MIT
  license_family: MIT
  license_file:
    - LICENSE
    - LICENSE_CRoaring

  summary: An efficient and light-weight ordered set of 32-bit integers
  description: |
    An efficient and light-weight ordered set of 32-bit integers
    This is a Python wrapper for the C library [CRoaring][1].

    [1]: https://github.com/RoaringBitmap/CRoaring

extra:
  recipe-maintainers:
    - stuarteberg
    - Ezibenroc
