{% set name = "pyroaring" %}
{% set version = "0.3.8" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  - url: https://github.com/Ezibenroc/PyRoaringBitMap/archive/{{ version }}.tar.gz
    sha256: c22fb9044e6745c6aaf829890c1bb09ef57dca0dbfa34fa72899c2813c21925c

build:
  number: 0
  script: {{ PYTHON }} -m pip install --no-deps --ignore-installed .

requirements:
  build:
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
  host:
    - python
    - pip
    - cython
  run:
    - python

test:
  imports:
    - pyroaring

about:
  home: https://github.com/Ezibenroc/PyRoaringBitMap
  dev_url: https://github.com/Ezibenroc/PyRoaringBitMap
  doc_url: https://pyroaringbitmap.readthedocs.io/en/stable/?badge=stable

  license: MIT
  license_family: MIT
  license_file:
    - LICENSE
    - LICENSE_CRoaring

  summary: An efficient and light-weight ordered set of 32-bit integers
  description: |
    An efficient and light-weight ordered set of 32-bit integers
    This is a Python wrapper for the C library [CRoaring][1].

    [1]: https://github.com/RoaringBitmap/CRoaring

extra:
  recipe-maintainers:
    - stuarteberg
    - Ezibenroc
